apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  default_user.conf: |
    default_user = guest
    default_pass = guest
  #host: dmF1bHQtZGVmYXVsdC11c2VyLmRlZmF1bHQuc3Zj
  username: guest
  password: guest
  #port: "5672"
  #provider: rabbitmq
  #type: rabbitmq